-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 10:34:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema redbus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema redbus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redbus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `redbus` ;

-- -----------------------------------------------------
-- Table `redbus`.`bus_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redbus`.`bus_routes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `route_name` TEXT NULL DEFAULT NULL,
  `route_link` TEXT NULL DEFAULT NULL,
  `busname` TEXT NULL DEFAULT NULL,
  `bustype` TEXT NULL DEFAULT NULL,
  `departing_time` DATETIME NULL DEFAULT NULL,
  `duration` TEXT NULL DEFAULT NULL,
  `reaching_time` DATETIME NULL DEFAULT NULL,
  `star_rating` FLOAT NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `seats_available` INT NULL DEFAULT NULL,
  `owner` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
